"""rol init

Revision ID: 0108f5e7731a
Revises:
Create Date: 2025-08-31 15:41:04.970334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0108f5e7731a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_rol',
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_rol_activo'), 'tbl_rol', ['activo'], unique=False)
    op.create_index(op.f('ix_tbl_rol_id'), 'tbl_rol', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_rol_nombre'), 'tbl_rol', ['nombre'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_rol_nombre'), table_name='tbl_rol')
    op.drop_index(op.f('ix_tbl_rol_id'), table_name='tbl_rol')
    op.drop_index(op.f('ix_tbl_rol_activo'), table_name='tbl_rol')
    op.drop_table('tbl_rol')
    # ### end Alembic commands ###
