"""crear tabla cliente

Revision ID: 1f798456d5e2
Revises: 707f1c89a4dc
Create Date: 2025-09-05 13:40:00.676186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1f798456d5e2'
down_revision: Union[str, None] = '707f1c89a4dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_cliente',
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_cliente_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['tbl_persona.id'], ),
    sa.ForeignKeyConstraint(['tipo_cliente_id'], ['tbl_tipo_cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_cliente_activo'), 'tbl_cliente', ['activo'], unique=False)
    op.create_index(op.f('ix_tbl_cliente_id'), 'tbl_cliente', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_cliente_persona_id'), 'tbl_cliente', ['persona_id'], unique=True)
    op.create_index(op.f('ix_tbl_cliente_tipo_cliente_id'), 'tbl_cliente', ['tipo_cliente_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_cliente_tipo_cliente_id'), table_name='tbl_cliente')
    op.drop_index(op.f('ix_tbl_cliente_persona_id'), table_name='tbl_cliente')
    op.drop_index(op.f('ix_tbl_cliente_id'), table_name='tbl_cliente')
    op.drop_index(op.f('ix_tbl_cliente_activo'), table_name='tbl_cliente')
    op.drop_table('tbl_cliente')
    # ### end Alembic commands ###
