"""crear tabla tipo cliente

Revision ID: 253c6fb93287
Revises: 254bbd4e3fa0
Create Date: 2025-09-02 16:15:38.463915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '253c6fb93287'
down_revision: Union[str, None] = '254bbd4e3fa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_tipo_cliente',
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('descuento', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    sa.CheckConstraint('descuento >= 0 AND descuento <= 100', name='ck_tbl_tipo_cliente_descuento_rango'),
    )
    op.create_index(op.f('ix_tipo_cliente_activo'), 'tbl_tipo_cliente', ['activo'], unique=False)
    op.create_index(op.f('ix_tipo_cliente_id'), 'tbl_tipo_cliente', ['id'], unique=False)
    op.create_index(op.f('ix_tipo_cliente_nombre'), 'tbl_tipo_cliente', ['nombre'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tipo_cliente_nombre'), table_name='tbl_tipo_cliente')
    op.drop_index(op.f('ix_tipo_cliente_id'), table_name='tbl_tipo_cliente')
    op.drop_index(op.f('ix_tipo_cliente_activo'), table_name='tbl_tipo_cliente')
    op.drop_table('tipo_cliente')
    # ### end Alembic commands ###
