"""crear tabla persona

Revision ID: 254bbd4e3fa0
Revises: 154699fe5d08
Create Date: 2025-09-02 13:21:07.736484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '254bbd4e3fa0'
down_revision: Union[str, None] = '154699fe5d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_persona',
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tipo_identificacion', postgresql.ENUM('CEDULA', 'RUC', 'PASAPORTE', name='tipo_identificacion_enum'), nullable=False),
    sa.Column('identificacion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('apellido', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('ciudad', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_persona_activo'), 'tbl_persona', ['activo'], unique=False)
    op.create_index(op.f('ix_tbl_persona_apellido'), 'tbl_persona', ['apellido'], unique=False)
    op.create_index(op.f('ix_tbl_persona_id'), 'tbl_persona', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_persona_identificacion'), 'tbl_persona', ['identificacion'], unique=True)
    op.create_index(op.f('ix_tbl_persona_nombre'), 'tbl_persona', ['nombre'], unique=False)
    op.create_index(op.f('ix_tbl_empresa_razon_social'), 'tbl_empresa', ['razon_social'], unique=False)
    op.drop_constraint('tbl_empresa_tipo_contribuyente_id_fkey', 'tbl_empresa', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_empresa', 'aux_tipo_contribuyente', ['tipo_contribuyente_id'], ['codigo'])
    op.alter_column('tbl_punto_emision', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tbl_punto_emision', 'creado_en',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tbl_punto_emision', 'actualizado_en',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tbl_punto_emision', 'descripcion',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=120),
               existing_nullable=False)
    op.drop_constraint('uq_codigo_por_entidad', 'tbl_punto_emision', type_='unique')
    op.create_index(op.f('ix_tbl_punto_emision_activo'), 'tbl_punto_emision', ['activo'], unique=False)
    op.create_unique_constraint('uq_pe_empresa_sucursal_codigo', 'tbl_punto_emision', ['empresa_id', 'sucursal_id', 'codigo'])
    op.alter_column('tbl_rol', 'usuario_auditoria',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tbl_sucursal', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tbl_sucursal', 'creado_en',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tbl_sucursal', 'actualizado_en',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tbl_sucursal', 'usuario_auditoria',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_tbl_sucursal_activo'), 'tbl_sucursal', ['activo'], unique=False)
    op.create_index(op.f('ix_tbl_sucursal_codigo'), 'tbl_sucursal', ['codigo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_sucursal_codigo'), table_name='tbl_sucursal')
    op.drop_index(op.f('ix_tbl_sucursal_activo'), table_name='tbl_sucursal')
    op.alter_column('tbl_sucursal', 'usuario_auditoria',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tbl_sucursal', 'actualizado_en',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('tbl_sucursal', 'creado_en',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('tbl_sucursal', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('tbl_rol', 'usuario_auditoria',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('uq_pe_empresa_sucursal_codigo', 'tbl_punto_emision', type_='unique')
    op.drop_index(op.f('ix_tbl_punto_emision_activo'), table_name='tbl_punto_emision')
    op.create_unique_constraint('uq_codigo_por_entidad', 'tbl_punto_emision', ['codigo', 'empresa_id', 'sucursal_id'])
    op.alter_column('tbl_punto_emision', 'descripcion',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('tbl_punto_emision', 'actualizado_en',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('tbl_punto_emision', 'creado_en',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('tbl_punto_emision', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_constraint(None, 'tbl_empresa', type_='foreignkey')
    op.create_foreign_key('tbl_empresa_tipo_contribuyente_id_fkey', 'tbl_empresa', 'aux_tipo_contribuyente', ['tipo_contribuyente_id'], ['codigo'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_tbl_empresa_razon_social'), table_name='tbl_empresa')
    op.drop_index(op.f('ix_tbl_persona_nombre'), table_name='tbl_persona')
    op.drop_index(op.f('ix_tbl_persona_identificacion'), table_name='tbl_persona')
    op.drop_index(op.f('ix_tbl_persona_id'), table_name='tbl_persona')
    op.drop_index(op.f('ix_tbl_persona_apellido'), table_name='tbl_persona')
    op.drop_index(op.f('ix_tbl_persona_activo'), table_name='tbl_persona')
    op.drop_table('tbl_persona')
    # ### end Alembic commands ###
