"""agregando tabla proveedor persona

Revision ID: 2c262aed5317
Revises: 0eb25a2376f7
Create Date: 2025-05-05 18:51:26.858271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c262aed5317'
down_revision: Union[str, None] = '0eb25a2376f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_proveedor_persona', sa.Column('nombre_comercial', sa.String(), nullable=True))
    op.add_column('tbl_proveedor_persona', sa.Column('tipo_contribuyente_id', sa.String(length=2), nullable=False))
    op.drop_constraint('tbl_proveedor_persona_tipo_contribuyente_codigo_fkey', 'tbl_proveedor_persona', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_proveedor_persona', 'aux_tipo_contribuyente', ['tipo_contribuyente_id'], ['codigo'])
    op.drop_column('tbl_proveedor_persona', 'cargo_contacto')
    op.drop_column('tbl_proveedor_persona', 'nombre_contacto')
    op.drop_column('tbl_proveedor_persona', 'telefono_contacto')
    op.drop_column('tbl_proveedor_persona', 'tipo_contribuyente_codigo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_proveedor_persona', sa.Column('tipo_contribuyente_codigo', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tbl_proveedor_persona', sa.Column('telefono_contacto', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tbl_proveedor_persona', sa.Column('nombre_contacto', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tbl_proveedor_persona', sa.Column('cargo_contacto', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tbl_proveedor_persona', type_='foreignkey')
    op.create_foreign_key('tbl_proveedor_persona_tipo_contribuyente_codigo_fkey', 'tbl_proveedor_persona', 'aux_tipo_contribuyente', ['tipo_contribuyente_codigo'], ['codigo'])
    op.drop_column('tbl_proveedor_persona', 'tipo_contribuyente_id')
    op.drop_column('tbl_proveedor_persona', 'nombre_comercial')
    # ### end Alembic commands ###
