"""Crear tablas usuarios, clientes, empleados, tipo cliente

Revision ID: 464d64766238
Revises: d81d118818ff
Create Date: 2025-05-02 15:17:54.211331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '464d64766238'
down_revision: Union[str, None] = 'd81d118818ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aux_tipo_cliente',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descuento', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tbl_empleado',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('salario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cargo', sa.String(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('fecha_salida', sa.Date(), nullable=True),
    sa.Column('activo', sa.String(), nullable=True),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('fecha_modificacion', sa.Date(), nullable=True),
    sa.Column('usuario_auditoria', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_cliente',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo_cliente_id', sa.UUID(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('usuario_auditoria', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tipo_cliente_id'], ['aux_tipo_cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_usuario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('rol_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('requiere_cambio_password', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('usuario_auditoria', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['tbl_persona.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['tbl_rol.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_usuario')
    op.drop_table('tbl_cliente')
    op.drop_table('tbl_empleado')
    op.drop_table('aux_tipo_cliente')
    # ### end Alembic commands ###
