"""fix fk tipo_contribuyente

Revision ID: 4847f320248a
Revises: 
Create Date: 2025-04-22 20:46:54.617117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4847f320248a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aux_tipo_contribuyente',
    sa.Column('codigo', sa.String(length=2), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_index(op.f('ix_aux_tipo_contribuyente_codigo'), 'aux_tipo_contribuyente', ['codigo'], unique=False)
    op.create_table('tbl_empresa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('razon_social', sa.String(), nullable=False),
    sa.Column('nombre_comercial', sa.String(), nullable=True),
    sa.Column('ruc', sa.String(length=13), nullable=False),
    sa.Column('direccion_matriz', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('codigo_establecimiento', sa.String(length=3), nullable=False),
    sa.Column('obligado_contabilidad', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('tipo_contribuyente_id', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['tipo_contribuyente_id'], ['aux_tipo_contribuyente.codigo'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_empresa_id'), 'tbl_empresa', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_empresa_ruc'), 'tbl_empresa', ['ruc'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_empresa_ruc'), table_name='tbl_empresa')
    op.drop_index(op.f('ix_tbl_empresa_id'), table_name='tbl_empresa')
    op.drop_table('tbl_empresa')
    op.drop_index(op.f('ix_aux_tipo_contribuyente_codigo'), table_name='aux_tipo_contribuyente')
    op.drop_table('aux_tipo_contribuyente')
    # ### end Alembic commands ###
