"""crear tabla empleado

Revision ID: 4c562293057c
Revises: 1f798456d5e2
Create Date: 2025-09-05 23:38:12.971357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c562293057c'
down_revision: Union[str, None] = '1f798456d5e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_empleado',
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.Column('salario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('fecha_salida', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['tbl_persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_empleado_activo'), 'tbl_empleado', ['activo'], unique=False)
    op.create_index(op.f('ix_tbl_empleado_id'), 'tbl_empleado', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_empleado_persona_id'), 'tbl_empleado', ['persona_id'], unique=True)
    op.drop_index('ix_tbl_cargo_activo', table_name='tbl_cargo')
    op.drop_index('ix_tbl_cargo_id', table_name='tbl_cargo')
    op.drop_index('ix_tbl_cargo_nombre', table_name='tbl_cargo')
    op.drop_table('tbl_cargo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_cargo',
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('creado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('actualizado_en', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('usuario_auditoria', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tbl_cargo_pkey')
    )
    op.create_index('ix_tbl_cargo_nombre', 'tbl_cargo', ['nombre'], unique=True)
    op.create_index('ix_tbl_cargo_id', 'tbl_cargo', ['id'], unique=False)
    op.create_index('ix_tbl_cargo_activo', 'tbl_cargo', ['activo'], unique=False)
    op.drop_index(op.f('ix_tbl_empleado_persona_id'), table_name='tbl_empleado')
    op.drop_index(op.f('ix_tbl_empleado_id'), table_name='tbl_empleado')
    op.drop_index(op.f('ix_tbl_empleado_activo'), table_name='tbl_empleado')
    op.drop_table('tbl_empleado')
    # ### end Alembic commands ###
