"""crear tabla usuario

Revision ID: 707f1c89a4dc
Revises: 253c6fb93287
Create Date: 2025-09-02 21:44:27.674323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '707f1c89a4dc'
down_revision: Union[str, None] = '253c6fb93287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_usuario',
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.Column('rol_id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('requiere_cambio_password', sa.Boolean(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['tbl_persona.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['tbl_rol.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id')
    )
    op.create_index(op.f('ix_tbl_usuario_activo'), 'tbl_usuario', ['activo'], unique=False)
    op.create_index(op.f('ix_tbl_usuario_id'), 'tbl_usuario', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_usuario_username'), 'tbl_usuario', ['username'], unique=True)
    op.alter_column('tbl_tipo_cliente', 'descuento',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index('ix_tipo_cliente_activo', table_name='tbl_tipo_cliente')
    op.drop_index('ix_tipo_cliente_id', table_name='tbl_tipo_cliente')
    op.drop_index('ix_tipo_cliente_nombre', table_name='tbl_tipo_cliente')
    op.create_index(op.f('ix_tbl_tipo_cliente_activo'), 'tbl_tipo_cliente', ['activo'], unique=False)
    op.create_index(op.f('ix_tbl_tipo_cliente_id'), 'tbl_tipo_cliente', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_tipo_cliente_nombre'), 'tbl_tipo_cliente', ['nombre'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_tipo_cliente_nombre'), table_name='tbl_tipo_cliente')
    op.drop_index(op.f('ix_tbl_tipo_cliente_id'), table_name='tbl_tipo_cliente')
    op.drop_index(op.f('ix_tbl_tipo_cliente_activo'), table_name='tbl_tipo_cliente')
    op.create_index('ix_tipo_cliente_nombre', 'tbl_tipo_cliente', ['nombre'], unique=True)
    op.create_index('ix_tipo_cliente_id', 'tbl_tipo_cliente', ['id'], unique=False)
    op.create_index('ix_tipo_cliente_activo', 'tbl_tipo_cliente', ['activo'], unique=False)
    op.alter_column('tbl_tipo_cliente', 'descuento',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_tbl_usuario_username'), table_name='tbl_usuario')
    op.drop_index(op.f('ix_tbl_usuario_id'), table_name='tbl_usuario')
    op.drop_index(op.f('ix_tbl_usuario_activo'), table_name='tbl_usuario')
    op.drop_table('tbl_usuario')
    # ### end Alembic commands ###
