"""crear tabla cargo

Revision ID: 9d1b66f939eb
Revises: 1f798456d5e2
Create Date: 2025-09-05 22:48:23.105315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9d1b66f939eb'
down_revision: Union[str, None] = '1f798456d5e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_cargo',
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_cargo_activo'), 'tbl_cargo', ['activo'], unique=False)
    op.create_index(op.f('ix_tbl_cargo_id'), 'tbl_cargo', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_cargo_nombre'), 'tbl_cargo', ['nombre'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_cargo_nombre'), table_name='tbl_cargo')
    op.drop_index(op.f('ix_tbl_cargo_id'), table_name='tbl_cargo')
    op.drop_index(op.f('ix_tbl_cargo_activo'), table_name='tbl_cargo')
    op.drop_table('tbl_cargo')
    # ### end Alembic commands ###
