"""

Revision ID: a9dec3e40201
Revises: f448962ca071
Create Date: 2025-09-21 01:35:32.455912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a9dec3e40201'
down_revision: Union[str, None] = 'f448962ca071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_proveedor_sociedad',
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ruc', sqlmodel.sql.sqltypes.AutoString(length=13), nullable=False),
    sa.Column('razon_social', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre_comercial', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_contribuyente_id', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('persona_contacto_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['persona_contacto_id'], ['tbl_persona.id'], ),
    sa.ForeignKeyConstraint(['tipo_contribuyente_id'], ['aux_tipo_contribuyente.codigo'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruc')
    )
    op.create_index(op.f('ix_tbl_proveedor_sociedad_activo'), 'tbl_proveedor_sociedad', ['activo'], unique=False)
    op.create_index(op.f('ix_tbl_proveedor_sociedad_id'), 'tbl_proveedor_sociedad', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_proveedor_sociedad_id'), table_name='tbl_proveedor_sociedad')
    op.drop_index(op.f('ix_tbl_proveedor_sociedad_activo'), table_name='tbl_proveedor_sociedad')
    op.drop_table('tbl_proveedor_sociedad')
    # ### end Alembic commands ###
