"""crear tabla sucursal

Revision ID: a9fde7c05625
Revises: 29d191364ad8
Create Date: 2025-04-24 03:17:05.809279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9fde7c05625'
down_revision: Union[str, None] = '29d191364ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_sucursal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=3), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['tbl_empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_punto_emision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=3), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('secuencial_actual', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('sucursal_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['tbl_empresa.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['tbl_sucursal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', 'empresa_id', 'sucursal_id', name='uq_codigo_por_entidad')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_punto_emision')
    op.drop_table('tbl_sucursal')
    # ### end Alembic commands ###
