"""crear tabla proveedor sociedad

Revision ID: d815b3994f1f
Revises: 2c262aed5317
Create Date: 2025-08-30 01:44:19.509765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd815b3994f1f'
down_revision: Union[str, None] = '2c262aed5317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_proveedor_sociedad',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ruc', sa.String(), nullable=False),
    sa.Column('razon_social', sa.String(), nullable=False),
    sa.Column('nombre_comercial', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('tipo_contribuyente_id', sa.String(length=2), nullable=False),
    sa.Column('persona_contacto_id', sa.UUID(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('usuario_auditoria', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['persona_contacto_id'], ['tbl_persona.id'], ),
    sa.ForeignKeyConstraint(['tipo_contribuyente_id'], ['aux_tipo_contribuyente.codigo'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_proveedor_sociedad')
    # ### end Alembic commands ###
