"""crear tabla empresa

Revision ID: e2bef79425b7
Revises: 70efb3f6be2f_tipo_contribuyente
Create Date: 2025-09-01 04:41:33.613078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e2bef79425b7'
down_revision: Union[str, None] = '70efb3f6be2f_tipo_contribuyente'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_empresa',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('razon_social', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre_comercial', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ruc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('direccion_matriz', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('codigo_establecimiento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('obligado_contabilidad', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('tipo_contribuyente_id', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['tipo_contribuyente_id'], ['aux_tipo_contribuyente.codigo'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_empresa_activo'), 'tbl_empresa', ['activo'], unique=False)
    op.create_index(op.f('ix_tbl_empresa_id'), 'tbl_empresa', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_empresa_ruc'), 'tbl_empresa', ['ruc'], unique=False)
    op.alter_column('aux_tipo_contribuyente', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_aux_tipo_contribuyente_codigo', table_name='aux_tipo_contribuyente')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_aux_tipo_contribuyente_codigo', 'aux_tipo_contribuyente', ['codigo'], unique=False)
    op.alter_column('aux_tipo_contribuyente', 'activo',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index(op.f('ix_tbl_empresa_ruc'), table_name='tbl_empresa')
    op.drop_index(op.f('ix_tbl_empresa_id'), table_name='tbl_empresa')
    op.drop_index(op.f('ix_tbl_empresa_activo'), table_name='tbl_empresa')
    op.drop_table('tbl_empresa')
    # ### end Alembic commands ###
