"""crear tabla proveedor_persona

Revision ID: f448962ca071
Revises: 4c562293057c
Create Date: 2025-09-07 00:02:29.241035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f448962ca071'
down_revision: Union[str, None] = '4c562293057c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_proveedor_persona',
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('usuario_auditoria', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre_comercial', sa.String(), nullable=True),
    sa.Column('tipo_contribuyente_id', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('persona_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['tbl_persona.id'], ),
    sa.ForeignKeyConstraint(['tipo_contribuyente_id'], ['aux_tipo_contribuyente.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_proveedor_persona_activo'), 'tbl_proveedor_persona', ['activo'], unique=False)
    op.create_index(op.f('ix_tbl_proveedor_persona_id'), 'tbl_proveedor_persona', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_proveedor_persona_id'), table_name='tbl_proveedor_persona')
    op.drop_index(op.f('ix_tbl_proveedor_persona_activo'), table_name='tbl_proveedor_persona')
    op.drop_table('tbl_proveedor_persona')
    # ### end Alembic commands ###
