"""Migraciones actualizadas

Revision ID: f9e4553d965e
Revises: a9fde7c05625
Create Date: 2025-05-02 04:01:23.971912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9e4553d965e'
down_revision: Union[str, None] = 'a9fde7c05625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_punto_emision', sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
    op.add_column('tbl_punto_emision', sa.Column('fecha_modificacion', sa.DateTime(), nullable=True))
    op.add_column('tbl_punto_emision', sa.Column('usuario_auditoria', sa.String(), nullable=True))
    op.add_column('tbl_sucursal', sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
    op.add_column('tbl_sucursal', sa.Column('fecha_modificacion', sa.DateTime(), nullable=True))
    op.add_column('tbl_sucursal', sa.Column('usuario_auditoria', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_sucursal', 'usuario_auditoria')
    op.drop_column('tbl_sucursal', 'fecha_modificacion')
    op.drop_column('tbl_sucursal', 'fecha_creacion')
    op.drop_column('tbl_punto_emision', 'usuario_auditoria')
    op.drop_column('tbl_punto_emision', 'fecha_modificacion')
    op.drop_column('tbl_punto_emision', 'fecha_creacion')
    # ### end Alembic commands ###
